services:
  - type: web
    name: lao-jobs
    runtime: python
    buildCommand: "./build.sh"
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.render
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: lao-jobs-db
    plan: free
    databaseName: lao_jobs
    user: lao_jobs_user
